import Link from "next/link";
import React from "react";

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <h1>About</h1>
      <Link href="/"> Go to home </Link>
    </>
  );
}
